fixed compilation with optimization enabled:
Ensure all variables are initialized before being used.

.../monetdb5/extras/rdf/rdfschema.c: In function 'RDFextractCSwithTypes':
.../monetdb5/extras/rdf/rdfschema.c:1716:15: error: 'sbt' may be used uninitialized in this function [-Werror=uninitialized]
.../monetdb5/extras/rdf/rdfschema.c:1671:9: note: 'sbt' was declared here
.../monetdb5/extras/rdf/rdfschema.c: In function 'RDFextractPfromPSO':
.../monetdb5/extras/rdf/rdfschema.c:1923:19: error: 'bt' may be used uninitialized in this function [-Werror=uninitialized]
.../monetdb5/extras/rdf/rdfschema.c:1916:6: error: 'curS' may be used uninitialized in this function [-Werror=uninitialized]